### ISSUE TITLE
No data available in table

### ISSUE THREAD

**Issue by adrien80080** [opi/linuxdash_ynh#1]
Bonjour !
J'ai un soucis avec Linux Dash.
Il est installé à la racine du domaine (ex : dash.domain.tld)
Mais voici ce qu'il m'affiche : https://img.abhd.fr/GjBDzcd2/gcxNHH5e

Je ne sais pas d'ou ça peut venir :/

**Comment by M5oul** [comment]
Pareil chez moi, ayant intallé sur `/dash`.

**Comment by opi** [comment]
M5oul is now maintain the Linux-Dash Yunohost application, see https://github.com/M5oul/linuxdash_ynh
